andOTP/andOTP

app/src/main/java/org/shadowice/flocke/andotp/Activities/BackupActivity.java

Old intent is supposed to be reused after user interaction.

Fixing #20

---

app/src/main/res/values-fr-rFR/strings_about.xml
app/src/main/res/values-fr-rFR/strings_auth.xml
app/src/main/res/values-fr-rFR/strings_backup.xml
app/src/main/res/values-fr-rFR/strings_main.xml
app/src/main/res/values-fr-rFR/strings_settings.xml

_Sorry for the previous PR, I fucked up between my accounts._
This commit adds French translation to the app.
I'm prone to do grammatical mistakes so a complete review by another French speaker would be appreciated.
I also don't know how to translate “Panic Trigger” in a short sentence.

Add french translation

---

README.md
app/src/androidTest/java/org/shadowice/flocke/andotp/ApplicationTest.java
app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
app/src/main/java/org/shadowice/flocke/andotp/Database/Entry.java
app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
app/src/main/java/org/shadowice/flocke/andotp/Utilities/TagDialogHelper.java
app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
app/src/main/java/org/shadowice/flocke/andotp/View/EntryViewHolder.java
app/src/main/java/org/shadowice/flocke/andotp/View/TagsAdapter.java
app/src/main/res/layout/component_card.xml
app/src/main/res/layout/component_tags.xml
app/src/main/res/layout/content_main.xml
app/src/main/res/layout/dialog_manual_entry.xml
app/src/main/res/menu/menu_popup.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/settings.xml
app/src/main/res/values/strings_main.xml

Fixes #37
This adds support for tagging entries, the tags can then be used to filter entries shown in the main view.

Tagging support

---

app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java
app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
app/src/main/java/org/shadowice/flocke/andotp/View/EntryViewHolder.java
app/src/main/res/values/settings.xml
app/src/main/res/values/strings_settings.xml
app/src/main/res/xml/preferences.xml

Fixes #98 
Currently this will just reset thumbnails settings (if user has thumbnails hidden), let me know if this is acceptable or if we need some mechanism to migrate

Move thumbnail toggle into the size selector

---

app/src/main/java/org/shadowice/flocke/andotp/Activities/AboutActivity.java
app/src/main/res/values/strings_about.xml

Copy to clipboard when opening the uri fails

---

app/src/main/java/org/shadowice/flocke/andotp/Activities/BackupActivity.java
app/src/main/java/org/shadowice/flocke/andotp/Utilities/Constants.java
app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
app/src/main/java/org/shadowice/flocke/andotp/Utilities/Tools.java
app/src/main/res/values/settings.xml
app/src/main/res/values/strings_settings.xml
app/src/main/res/xml/preferences.xml

Allows option to auto append the current date-time to the backup filename

Append date backup

---

app/src/main/java/org/shadowice/flocke/andotp/View/ManualEntryDialog.java

Check if "Advanced Options" are valid before enabling the "Save" button

---

app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
app/src/main/java/org/shadowice/flocke/andotp/Utilities/Constants.java
app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
app/src/main/java/org/shadowice/flocke/andotp/View/TagsAdapter.java
app/src/main/res/values/settings.xml
app/src/main/res/values/strings_settings.xml
app/src/main/res/xml/preferences.xml

Add setting to select different tags behaviour

---

app/src/main/AndroidManifest.xml
app/src/main/res/layout/component_intro_encryption.xml

Scrollbars and no need for landscape orientation on the Intro Screens

Added Scroll to the Database Encryption fragment on Intro screen and forced portrait orientation

---

app/src/main/java/org/shadowice/flocke/andotp/Activities/AuthenticateActivity.java

Support SDK API 23 on empty PIN code

---

app/src/main/res/values/strings_settings.xml

Thanks for andOTP! It's a great app.

Fixed typo in strings_settings.xml

---

app/src/main/res/layout/component_authentication.xml
app/src/main/res/layout/component_intro_authentication.xml
app/src/main/res/layout/component_password.xml
app/src/main/res/layout/content_authenticate.xml

Add autofill hints to password fields

---

app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java
app/src/main/res/drawable/thumb_1password.xml

Source: https://i.1password.com/akb/featured/1password-icon.svg
Test Screenshot:

EntryThumbnail: Add 1Password thumb

---

app/src/main/res/values-ca-rES/strings_main.xml
app/src/main/res/values-de-rDE/strings_main.xml
app/src/main/res/values-fr-rFR/strings_main.xml
app/src/main/res/values-it-rIT/strings_main.xml
app/src/main/res/values-zh-rTW/strings_main.xml
app/src/main/res/values/strings_main.xml

This commit fixes spelling of "QR code".

QR-Code -> QR code

---

app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java

Fix all tags only selecting visible tags

---

app/src/main/res/xml/preferences.xml

Enable android backup by default

---

app/src/main/java/org/shadowice/flocke/andotp/View/ManualEntryDialog.java

@flocke, I tried with IFTTT 2FA which has spaces in it's secret and it seems to work with or without my change. If this is something that you've already fixed, you can decline my pull request.

#253 Remove whitespaces in secret when added manually

---

app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
app/src/main/java/org/shadowice/flocke/andotp/Database/Entry.java
app/src/main/java/org/shadowice/flocke/andotp/Utilities/Constants.java
app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
app/src/main/res/menu/menu_main.xml
app/src/main/res/values/settings.xml
app/src/main/res/values/strings_main.xml

Sorts entries by most uses based on copies and token reveals.
@flocke, I couldn't think of an icon for this sort method, so I have used the same icon as 'Last used '

Added 'Most Used' sort option #443

---

app/src/main/java/org/shadowice/flocke/andotp/Database/Entry.java
app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
app/src/main/res/menu/menu_popup.xml
app/src/main/res/values/strings_main.xml

This way a account can be easily copied to a different device. For example to a different implementation that doesn't support the custom backup format.

Add the ability to show qr codes of stored accounts

---

README.md

Per https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md

Fixing fdroid button in README

---

app/src/main/res/values/strings_auth.xml
app/src/main/res/values/strings_intro.xml
app/src/main/res/values/strings_main.xml

Some suggested changes to English strings, referencing #149

#149 English String suggestions

---

.github/ISSUE_TEMPLATE/thumbnail-request.md

add @ziegenberg to thumbnail request issue template

---

app/src/main/java/org/shadowice/flocke/andotp/View/EntryViewHolder.java

Make sure that we have a valid adapter position before issuing callbacks that require position.

#631 - Fix NPE from invalid adapter position

---

app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
app/src/main/res/values/settings.xml
app/src/main/res/values/strings_settings.xml
app/src/main/res/xml/preferences.xml

added option to focus the search immediately after opening the app

---

app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/values/strings_main.xml

Added dataset oberver on adapter to hide the progress bar and add an empty view with instructions when the list is empty

Added feature to hide progress bar and add an instruction if there are no cards in the list #745 #746

---

app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
app/src/main/java/org/shadowice/flocke/andotp/View/EntryViewHolder.java
app/src/main/res/values/settings.xml
app/src/main/res/values/strings_settings.xml
app/src/main/res/xml/preferences.xml

@flocke , let me know if you want this option to be per card

Added option to hide issuer label #678

---

app/src/main/java/org/shadowice/flocke/andotp/Dialogs/PasswordEntryDialog.java
app/src/main/java/org/shadowice/flocke/andotp/Preferences/CredentialsPreference.java
app/src/main/res/layout/component_authentication.xml
app/src/main/res/layout/dialog_password_entry.xml

Adds a warning about password length in the password entry dialog until the length is met. Similar to what we have in CredentialsPreferences.java
This is how it looks:
https://user-images.githubusercontent.com/10265443/108588231-0e6c8a80-737e-11eb-9fbe-d576405b23be.mp4

Added password length check while creating backups #770

---

app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java
app/src/main/res/drawable/thumb_code42.xml

Issue: https://github.com/andOTP/andOTP/issues/776

EntryThumbnail: Add Code42 thumb
