app/src/main/AndroidManifest.xml, app/src/main/java/org/shadowice/flocke/andotp/Activities/PanicResponderActivity.java
After reading https://github.com/flocke/andOTP/issues/23#issuecomment-321928171
I realized that it would be a nice feature to have.
When the user triggers a Panic action the user preferences and secrets database are wiped.
The user will be able to restore from a secure backup when she's in a safe place.
Let me know if there's something that needs to be changed/added for it to be merged.
Cheers 😄
=> Added support to Panic trigger.

README.md
The second account was accidently created by me, using the wrong login provider...
I've already deleted the account.
=> Remove duplicate credits for german translation

app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
Doing ascii sort on natural language text will result in unexpected sorting. ie: Lowercase words being sorted after uppercase block or accents messing ordering.
Previous behaviour:
- A
- D
- a
- b
Current behaviour:
- a
- A
- b
- D
=> Label sort should be alphabetical and locale-sensitive

app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java, app/src/main/res/drawable/thumb_trello.xml
Resized to 198x198. SVG source: trello-mark-blue.svg from https://trello.com/about/logo
=> Add a thumbnail for Trello

build.gradle
Fetch dependencies from Google's repository first. Prevents a build failure caused by missing artifacts in JCenter.
```
FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find common.jar (android.arch.core:common:1.1.0).
Searched in the following locations:
https://jcenter.bintray.com/android/arch/core/common/1.1.0/common-1.1.0.jar
```
=> Fixes #190: Changes the import order of gradle repositories.

app/src/main/java/org/shadowice/flocke/andotp/Activities/ThemedActivity.java, build.gradle
Updates the existing configuration on a config change instead of overriding
existing settings.
This should fix the issue for now, but still calls the deprecated method `updateConfiguration`.
=> Fixes #71: Use Android's font size settings

app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java, app/src/main/res/drawable/thumb_hetzner.xml
This PR adds an icon for Hetzner Online GmbH, a german internet hosting company.
The source is here: https://www.hetzner.com/themes/hetzner/images/favicons/safari-pinned-tab.svg
I have splitted the logo in two separate paths in order to have a white foreground instead of transparent.
=> Add icon for Hetzner Online

app/src/main/res/layout/component_card.xml
In response to #262 I solved the appearance of the OTP in RTL layout by making it LTR forcefully.
I think this problem was very crucial and must be solved ASAP. The app needs more work on RTL support and Persian translation which will be submitted later.
=> Made OTP forcfully LTR

app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
Currently, if you filter in MainActivity and send the app to the background and restore it again, the filter-string is still displayed, but the list is not filtered:
This changes stores the last applied filter string in a field and saves it in the app-bundle to ensure its corrctly restored after onCreate and also onResume
=> ensure the filterstate is correctly applied after onCreate and onRestore

app/src/main/res/values-v27/styles.xml, app/src/main/res/values/styles.xml
I'd really like it if the light theme used a white system navbar. 
Comparison below.
The main purpose is to mitigate burn-in on OLED screen phones.
Personally, the phones I have owned with OLED screens have had significant burn-in around the system navbar after a year.
The original black system navbar is still used in dark and black themes for those who want the option.
What I did is created a "values-v27" folder and a "styles.xml".
In each theme I added the two items:
```
<item name="android:navigationBarColor"></item>
<item name="android:windowLightNavigationBar"></item>
```
Feedback and input is appreciated.
=> White navbar in light theme

app/src/main/java/org/shadowice/flocke/andotp/Database/Entry.java, app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
This PR fixes #334. As stated there, it should be possible to generate a new code when the HOTP token is visible - this is the same functionality Google Authenticator provides.
First, I added a new method similar to `isTimeBased()` called `isCounterBased()`. I think it's just nicer than checking for the type. I expected that there's a "counterpart" to `isTimeBased()` so I added it.
Secondly, I refactored the HOTP regenerating code to its own method.
Lastly, in the `onCardClicked` event I check if it's a counter based entry and call the `updateEntry()` method, the same way the counter click event handles it.
=> Instantly generate new code when showing hidden code for HOTP token

app/src/main/java/org/shadowice/flocke/andotp/Database/Entry.java, app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java, app/src/main/java/org/shadowice/flocke/andotp/View/EntryViewHolder.java, app/src/main/java/org/shadowice/flocke/andotp/View/ManualEntryDialog.java, app/src/main/res/layout/component_card.xml, app/src/main/res/layout/dialog_manual_entry.xml, app/src/main/res/menu/menu_popup.xml, app/src/main/res/values/strings_main.xml
This PR accomplishes what requested in issue #258: issuer and label are now stored separately in the database and are shown on two different lines for each entry.
For backward compatibility with older backup version, if the issuer entry is not found in the backup, the issuer is set to an empty string.
=> Fix #258: save and show issuer and label separately

app/src/main/java/org/shadowice/flocke/andotp/Database/Entry.java, app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java, app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java, app/src/main/java/org/shadowice/flocke/andotp/View/EntryViewHolder.java, app/src/main/java/org/shadowice/flocke/andotp/View/ManualEntryDialog.java, app/src/main/res/layout/component_card.xml, app/src/main/res/layout/dialog_manual_entry.xml, app/src/main/res/menu/menu_popup.xml, app/src/main/res/values/strings_main.xml
Fixes #388 based on changes provided by #372.
Both manual and QR code based addition of entries will check available icons for provided issuer.
If not null or matching (case insensitive) it will add the icon to the entry. Fallback to Default thumbnail still exists.
=> Add automatic icon mapping if issuer is provided

app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
This is a potential workaround for #264.
In this commit the OTP CardList (and with this, it's children) gets hidden when the AuthMethod is set to Device Credentials and the Activity gets paused. On resume the CardList will be made visible again if it's not, regardless of AuthMethod to prevent the CardList staying invisible when changing to other AuthMethods.
Turning the CardList invisible is run on the UI thread so the change is made before the UI Queue stops. If we don't do this, the change is not made when the screen is turned off while the Activity is active. E.g. on time-out or turning the screen of by using the power button the change would not be made in time.
=> Workaround: Hide otp card on screen off (#264)

app/src/main/java/org/shadowice/flocke/andotp/Activities/ThemedActivity.java, app/src/main/res/values-v27/styles.xml, app/src/main/res/values/styles.xml
Oxygen OS doesn't respect android:navigationBarColor if it's set to black in xml. This is to prevent burn in on the screen. More information can be found [here](https://forums.oneplus.com/threads/cannot-set-navigation-bar-color-to-pure-black-ff000000-via-values-xml.908719/)
A workaround would be to set the navigation bar color programmatically using [setNavigationBarColor()](https://developer.android.com/reference/android/view/Window.html#setNavigationBarColor(int))
I've implemented this workaround and tested on Pixel 3 in emulator and on my OnePlus 7 Pro
=> Fixed black navigation bar for OxygenOS devices #408

app/src/main/AndroidManifest.xml, app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java, app/src/main/res/values/strings_main.xml
Even if I didn't have any problems in the past with adding a new 2FA entry, now andOTP acts as receiver for `otpauth` links/data. This PR follows the discussion in  #324.
This is based on current master, so automatic tumbnail mapping and the split into separate issuer is not presented in the demo gif 👇
=> Implemented intent-filter to receive otpauth requests

app/src/main/res/values/settings.xml
the correct "simplified Chinese" word in Chinese(simplified) is 简体中文 not 簡體中文 ,簡體中文 is a Chinese(traditional) word.
=> change 簡體中文 to 简体中文

app/src/main/res/layout/dialog_manual_entry.xml
When manually entering details, the secret is currently visible and completed by the keyboard. This may occur learning of the secret by the keyboard. In order to prevent this, use inputType "textVisiblePassword". This keeps the secret visible but disables auto-completion.
=> dialog_manual_entry.xml: do not use auto-completion for secret

app/src/main/java/org/shadowice/flocke/andotp/View/EntryViewHolder.java
Implemented #487 
Added simple transparency setting in onItemSelected() (sets transparency to 0.5f) and in onItemClear() (sets transparency to 0.5f)
Tested on my OnePlus 7 Pro and for both light and dark themes.
=> Added transparency to the card if it's selected to be reordered in the list

app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java, app/src/main/res/drawable/thumb_weclapp.xml
Add icon for [weclapp](https://www.weclapp.com), extracted from here: https://www.weclapp.com/wp-content/uploads/2019/08/weclapp-presskit.zip
@ertanoe Do you approve this usage of the artwork?
=> Add weclapp icon

app/src/main/java/org/shadowice/flocke/andotp/Activities/IntroScreenActivity.java, app/src/main/res/layout/component_intro_authentication.xml
Set an end icon click listener and set the appropriate transformation method on the new password and confirm fields. 
Apologies for the somewhat messy PR, the work to fix #580 is all in [5e40bb3](https://github.com/andOTP/andOTP/commit/5e40bb3ea323c29e046677fd64a9362714011885) and the other commit is just a bit of code cleanup.
=> #580 confirm password field visibility

app/src/main/java/org/shadowice/flocke/andotp/Activities/IntroScreenActivity.java, app/src/main/java/org/shadowice/flocke/andotp/Dialogs/PasswordEntryDialog.java, app/src/main/java/org/shadowice/flocke/andotp/Preferences/CredentialsPreference.java, app/src/main/java/org/shadowice/flocke/andotp/Preferences/PasswordEncryptedPreference.java, app/src/main/java/org/shadowice/flocke/andotp/Utilities/ConfirmedPasswordTransformationHelper.java, app/src/main/res/layout/component_authentication.xml, app/src/main/res/layout/component_password.xml, app/src/main/res/layout/content_authenticate.xml, app/src/main/res/layout/dialog_password_entry.xml
Added a utility for setting input/confirmation password transformation since it's used in multiple places. Converted all views that have a password confirmation to use this utility, so that show/obscure password toggle state is shared between input and confirm.
**Tests performed to verify changes:**
1. Tested inputting password/PIN in initial intro activity (`IntroScreenActivity`)
1. Tested changing password/PIN for "Authentication" preference in Settings (`CredentialsPreference`)
1. Tested inputting password/PIN for encrypted backup/restore (`PasswordEntryDialog`)
1. Tested setting password for "Backup Password" preference in Settings (`PasswordEncryptedPreference`)
=> #638 - Convert all password views with confirmation field to share toggle state

app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java, app/src/main/java/org/shadowice/flocke/andotp/Activities/SettingsActivity.java, app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
Began unregistering Shared Pref listeners on activities that have been destroyed. This ensures that we aren't getting callbacks to a destroyed activities, and also that we're not potentially modifying shared preferences multiple times (since a new listener would be registered on each activity creation).
Unrelated cleanup, set some fields in SettingsActivity to be private (since they weren't being used elsewhere).
=> #639 Shared Preference NPE Fix

app/src/main/java/org/shadowice/flocke/andotp/Activities/IntroScreenActivity.java, app/src/main/java/org/shadowice/flocke/andotp/Activities/SettingsActivity.java, app/src/main/java/org/shadowice/flocke/andotp/Utilities/BackupAgent.java, app/src/main/res/layout/component_intro_android_sync.xml, app/src/main/res/values/strings_intro.xml, app/src/main/res/values/strings_settings.xml
Fix #620 
Adds an option to disable android sync to the initial flow
=> Add android sync to initial flow

.github/ISSUE_TEMPLATE/thumbnail-request.md
Comment thumbnail request instructions.
This way the user still sees the instructions when editing their request, but afterwards they aren't shown in the issue thread.
In the thread they aren't really needed and feel kinda out of place.
=> Comment thumbnail request instructions

app/src/main/java/org/shadowice/flocke/andotp/Preferences/CredentialsPreference.java
Sorry, it looks like I actually added this initial bug in commit b0c56b3 (I wasn't setting the input type when switching to password). I changed that, and fixed a few other small bugs that I found while looking at it:
- Began clearing the input fields when switching auth methods. We weren't doing this before, and you could technically therefore switch from password (entering alpha chars) and back to PIN and save it as long as they matched up. This is an unlikely case that the user would have to actively try to mess up, but it would mean you wouldn't be able to login (since the user would only be presented with a number keyboard when logging in later on).
- Began hiding the keyboard on proper input when switching auth methods. Before the keyboard wasn't being hidden when choosing …
=> #740 authentication dialog keyboard switch

app/src/main/java/org/shadowice/flocke/andotp/Activities/AuthenticateActivity.java, app/src/main/java/org/shadowice/flocke/andotp/Activities/BaseActivity.java, app/src/main/java/org/shadowice/flocke/andotp/Tasks/AuthenticationTask.java, app/src/main/java/org/shadowice/flocke/andotp/Tasks/UiBasedBackgroundTask.java, app/src/main/res/layout/content_authenticate.xml
Ok, so I added an ASyncTask to run the authentication code, with a callback to the Activity when it completes (still finishing the Activity on the main thread). While the task is running, I added an indeterminate progress bar that replaces the "unlock" button to provide some feedback to the user: 
https://user-images.githubusercontent.com/1057406/106338658-56f2c580-6262-11eb-8816-9c88006b6d2f.mp4
One small caveat here is that I call `.get()` on the task if the Activity is being paused. I did this to prevent the task from calling back to a dead activity for the case where the user initiates the unlock process and rotates their phone (or some other config change). 
If this situation happens, the task will complete and the Activity will finish as expected, however the main thread will be …
=> #635 move authentication to a background thread

app/src/main/java/org/shadowice/flocke/andotp/Activities/IntroScreenActivity.java, app/src/main/res/values/strings_intro.xml
I noticed that on the password initialization screen you get the same error message whether you have an empty confirm field or a mismatched confirm field, which appears like the app doesn't register the confirm field has text. This could be confusing to users if they accidentally hit an extra key and don't realize that there's an extra character in the confirm field. I propose adding an additional warning message for the case where the user has entered a confirm value, but it doesn't match the password value.
=> Added password mismatch warning for intro screen

app/src/main/java/org/shadowice/flocke/andotp/Database/Entry.java, app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java
This allows us to, e.g., use the GitLab icon when the issuer is `gitlab.com` but also when it is `gitlab.gnome.org`.
Fixes #685.
=> Use an thumbnail if its name appears as a word in the TOTP issuer field

app/build.gradle, app/src/main/java/org/shadowice/flocke/andotp/Utilities/ScanQRCodeFromFile.java
Try decoding the image multiple times with different decoding hints and update dependency _ZXing_ to version 3.4.1. to FIX #790.
Note: Although the documentation says that from `com.google.zxing:core` version 3.4.0 and later Java 8, which requires targeting API level 24 or later, is required, using Java 8 desugaring is a possible solution. For details see: https://developer.android.com/studio/write/java8-support
Java 8 desugaring was enabled for andOTP with #544 (commit df6c7cd41625dc714b73b727c55a34ae0c96839a) and is available since 0.8.0.
I tested this with the Android emulator on API Level 22 and 30.
=> fix QR code not found in image file

README.md
Proposing an addition to the "opening backups on your PC" section with an Electron-based app for macOS desktop.
=> Add mac2fa to PC apps section in README

app/src/main/java/org/shadowice/flocke/andotp/Utilities/Constants.java, app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java, app/src/main/res/menu/menu_popup.xml, app/src/main/res/values-de/strings_main.xml, app/src/main/res/values-de/strings_settings.xml, app/src/main/res/values/settings.xml, app/src/main/res/values/strings_main.xml, app/src/main/res/values/strings_settings.xml
Add the feature to share the current OTP via an Intent with the special mime-type "text/keystrokes"
Other apps could listen for this intents and pass the data to a connected desktop or other device where the 2FA code is needed.
I have also an open pull request on [KdeConnect](https://invent.kde.org/network/kdeconnect-android/-/merge_requests/220) which implements this functionality and it feels quite handy to pass the 2FA to the desktop. 
See here for a screen recording on how it works: https://imgur.com/a/uwjbESq / https://imgur.com/a/cBm5yOi
ToDo: maybe make it more visible or explain it somewhere in the app, so that users can find how to set this up (if no app is installed that explicitly filters for this mime type, the normal android chooser lets you share the text with any other app)
=> Add the feature to share the current OTP via an Intent

app/src/main/java/org/shadowice/flocke/andotp/Activities/SecureCaptureActivity.java
FIXES #806.
The `Activity#setContentView(int)` in `CaptureActivity#initializeContent()` of the superclass needs to be called before `getInsetsController()`, otherwise, an NPE will be thrown because the top-level view of the current Window, containing the window decor, is not yet initialized.
=> Fix scan QR code on android 11

README.md
This PR adds go-andotp (https://github.com/grijul/go-andotp) as an option to open andOTP decrypted files on PC.
go-andotp supports:
- Encryption of JSON files (which can then be imported to andOTP)
- Decryption of JSON files.
=> Added go-andotp for opening backups on PC
